# Generated by Django 3.2.16 on 2023-02-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='DormInfo',
            fields=[
                ('dorm_id', models.SmallIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='寝室号')),
                ('accom_num', models.SmallIntegerField(default=0, verbose_name='入住人数')),
                ('on_canpus_num', models.SmallIntegerField(default=0, verbose_name='实际在校人数')),
                ('administrator', models.CharField(max_length=32, verbose_name='寝室长')),
                ('admin_mobile', models.CharField(max_length=11, verbose_name='寝室长电话号码')),
                ('electric_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='电费余额')),
                ('level', models.SmallIntegerField(choices=[(1, '一星寝室'), (2, '二星寝室'), (3, '三星寝室'), (4, '优秀寝室'), (5, '最佳寝室')], default=1, verbose_name='等级')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='员工姓名')),
                ('password', models.CharField(max_length=64, verbose_name='password')),
                ('age', models.IntegerField(verbose_name='age')),
                ('account', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='账户余额')),
                ('create_time', models.DateField(verbose_name='入职时间')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('dorm', models.SmallIntegerField(default=111, verbose_name='寝室号')),
                ('mobile', models.CharField(default='00000000000', max_length=11, verbose_name='电话号码')),
            ],
        ),
    ]
