# Generated by Django 3.2.16 on 2023-02-14 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20230215_0658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticalPost',
        ),
    ]
